Added Favicon And Logo
iiitv/arcadia-web pull request #17
Opened 2018-07-28 06:53 UTC by rossoskull

ping @aashutoshrathi

2018-07-28 08:29 UTC, aashutoshrathi commented
Is this being updated on Pythonanywhere as well?

2018-07-28 08:32 UTC, rossoskull commented
I don't have any idea about that

2018-07-28 19:50 UTC, Monal5031 commented
@aashutoshrathi want to setup auto-deployment?

2018-07-28 19:51 UTC, Monal5031 requested changes
This PR is for favicon and logo right? then why migration files are being deleted?
Also amend your commit to reflect the changes done properly.

2018-07-28 19:51 UTC, Monal5031 commented on arc/teams/static/arcadia/style.css
>  }
newline

2018-07-29 05:18 UTC, rossoskull commented
@Monal5031 The .pyc files change every time I run the server. Also they are not ignored by gitignore. So they are changes automatically. And about the changes in css file, they are for proper positioning and sizing of the logo.

2018-08-03 11:32 UTC, merged